services:
  backend:
    build: ./backend
    container_name: backend
    network_mode: host

  frontend:
    build: ./frontend
    container_name: frontend
    network_mode: host
    environment:
      - BACKEND_URL=http://localhost:7860
    depends_on:
      - backend
